---

- name: "Generate encrypted grub password"
  shell: 
  register: grub_password

- name: "MEDIUM | V-38585 | Systems must require authentication upon booting into single-user and maintenance modes."
  lineinfile:
      state: present
      path: /boot/grub/grub.conf
      regexp: '^password --encrypted '
      insertafter: '^hiddenmenu'
      line: password --encrypted ${grub_password.stdout} 
  tags:
      - cat2-password
      - RHEL-06-00068
      - SV-50386r4_rule
      - V-38585
