---
- name: "LOW | V-38676 | The xorg-x11-server-common (X Windows) package must not be installed, unless required."
  yum:
      name:
          - "@X Windows System"
          - xorg-x11-server-common
      state: absent
  tags:
      - cat3
      - low
      - RHEL-06-000291
      - SV-50477r2_rule
      - V-38676

- name: "MEDIUM | V-38676 | Change graphical runlevel from 5 to 3."
  lineinfile:
      dest: /etc/inittab
      regexp: 'id:5:initdefault:'
      line: 'id:3:initdefault:'
  tags:
      - cat3
      - low
      - RHEL-06-000291
      - SV-50477r2_rule
      - V-38676

- name: "MEDIUM | V-38676 | Reset graphical mode to non-graphical."
  command: init 3
  tags:
      - cat3
      - low
      - RHEL-06-000291
      - SV-50477r2_rule
      - V-38676

