#!/bin/bash

system_auth="/etc/pam.d/system-auth"
system_auth_ac="/etc/pam.d/system-auth-ac"
password_auth="/etc/pam.d/password-auth"
password_auth_ac="/etc/pam.d/password-auth-ac"


if [[ $(grep '^auth.* required.* pam_faillock.so' "$system_auth") ]]; then
  sed -i 's/^auth.* required.* pam_faillock.so.*/auth    required    pam_faillock.so preauth silent deny=3 unlock_time=604800 fail_interval=900/' "$system_auth"
else
  sed -i '/^auth.* required.* pam_env.so/s/.*/&\nauth    required    pam_faillock.so preauth silent deny=3 unlock_time=604800 fail_interval=900/' "$system_auth"
fi

#if [[ $(grep '^auth.* [default=die].* pam_faillock.so' "$system_auth") ]]; then
#  sed -i 's/^auth.* [default=die].* pam_faillock.so.*/auth    [default=die]    pam_faillock.so authfail deny=3 unlock_time=604800 fail_interval=900/' "$system_auth"
#fi

#if [[ $(grep '^account.* required.* pam_faillock.so' "$system_auth") ]]; then
#  sed -i 's/^account.* required.* pam_faillock.so.*/account    required    pam_faillock.so/' "$system_auth"
#fi




#if [[ $(grep '^password.* sufficient.* pam_unix.so' "$system_auth_ac") ]]; then
#  sed -i 's/^password.* sufficient.* pam_unix.so.*/password    sufficient    pam_unix.so sha512 shadow try_first_pass use_authtok/' "$system_auth_ac"
#fi


#if [[ $(grep '^password.* sufficient.* pam_unix.so' "$password_auth") ]]; then
#  sed -i 's/^password.* sufficient.* pam_unix.so.*/password    sufficient    pam_unix.so sha512 shadow try_first_pass use_authtok remember=5/' "$password_auth"
#fi


#if [[ $(grep '^password.* sufficient.* pam_unix.so' "$password_auth_ac") ]]; then
#  sed -i 's/^password.* sufficient.* pam_unix.so.*/password    sufficient    pam_unix.so sha512 shadow try_first_pass use_authtok/' "$password_auth_ac"
#fi
