---
- name: "LOW | V-71987 | The operating system must remove all software components after updated versions have been installed."
  lineinfile:
      dest: /etc/yum.conf
      regexp: clean_requirements_on_remove
      line: clean_requirements_on_remove=1
      insertafter: '\[main\]'
  tags:
      - cat3
      - low
      - RHEL-07-020200
      - SV-86611r1_rule
      - V-71987

- name: "LOW | V-72003 | All Group Identifiers (GIDs) referenced in the /etc/passwd file must be defined in the /etc/group file."
  command: "true"
  tags:
      - cat3
      - low
      - RHEL-07-020300
      - SV-86627r1_rule
      - V-72003

- name: "LOW | V-72059 | A separate file system must be used for user home directories (such as /home or an equivalent)."
  command: "true"
  tags:
      - cat3
      - low
      - RHEL-07-021310
      - SV-86683r1_rule
      - V-72059

- name: "LOW | V-72061 | The system must use a separate file system for /var."
  command: "true"
  tags:
      - cat3
      - low
      - RHEL-07-021320
      - SV-86685r1_rule
      - V-72061

- name: "LOW | V-72063 | Install AIDE."
  yum:
      name: aide
      state: present
  tags:
      - cat3
      - medium
      - RHEL-07-021330
      - SV-86687r3_rule
      - V-72063

- name: "LOW | V-72063 | Check if /etc/aide.conf exists."
  stat: path=/etc/aide.conf
  register: v_72063_check
  tags:
      - cat3
      - medium
      - RHEL-07-021330
      - SV-86687r3_rule
      - V-72063

- name: "LOW | V-72063 | The file integrity tool must use FIPS 140-2 approved cryptographic hashes for validating file contents and directories."
#Repeat of CAT II V-72063
  script: v-72073.sh
  when: v_72063_check.stat.exists == True
  tags:
      - cat3
      - medium
      - RHEL-07-021330
      - SV-86687r3_rule
      - V-72063

- name: "LOW | V-72065 | The system must use a separate file system for /tmp (or equivalent)."
  command: "true"
  tags:
      - cat3
      - low
      - patch
      - RHEL-07-021340
      - SV-86689r1_rule
      - V-72065

- name: "LOW | V-72069 | The file integrity tool must be configured to verify Access Control Lists (ACLs)."
#Repeat of CAT II V-72073 AND CAT III V-72063
  yum:
      name: aide
      state: present
  tags:
      - cat3
      - low
      - RHEL-07-021600
      - SV-86693r2_rule
      - V-72069

- name: "LOW | V-72069 | Check if /etc/aide.conf exists."
  stat: path=/etc/aide.conf
  register: v_72069_check
  tags:
      - cat3
      - medium
      - RHEL-07-021600
      - SV-86693r2_rule
      - V-72069

- name: "LOW | V-72069 | The file integrity tool must use FIPS 140-2 approved cryptographic hashes for validating file contents and directories."
  script: v-72073.sh
  when: v_72069_check.stat.exists == True
  tags:
      - cat3
      - medium
      - RHEL-07-021600
      - SV-86693r2_rule
      - V-72069

- name: "LOW | V-72071 | The file integrity tool must be configured to verify extended attributes."
#Repeat of CAT II V-72073, CAT III V-72063, CAT III V-72069
  yum:
      name: aide
      state: present
  tags:
      - cat3
      - low
      - RHEL-07-021610
      - SV-86695r2_rule
      - V-72071

- name: "LOW | V-72071 | Check if /etc/aide.conf exists."
  stat: path=/etc/aide.conf
  register: v_72071_check
  tags:
      - cat3
      - medium
      - RHEL-07-021610
      - SV-86695r2_rule
      - V-72071

- name: "LOW | V-72071 | The file integrity tool must be configured to verify extended attributes."
  script: v-72073.sh
  when: v_72071_check.stat.exists == True
  tags:
      - cat3
      - low
      - RHEL-07-021610
      - SV-86695r2_rule
      - V-72071

- name: "LOW | V-72217 | The operating system must limit the number of concurrent sessions to 10 for all accounts and/or account types."
  lineinfile:
      dest: /etc/security/limits.conf 
      regexp: 'hard maxlogins'
      line: '* hard maxlogins 10'
  tags:
      - cat3
      - low
      - RHEL-07-040000
      - SV-86841r1_rule
      - V-72217

- name: "LOW | V-72275 | The system must display the date and time of the last successful account logon upon logon."
  lineinfile:
       dest: /etc/pam.d/postlogin-ac
       regexp: 'session     required      pam_lastlog.so showfailed silent'
       line: 'session     required      pam_lastlog.so showfailed'
  tags:
      - cat3
      - low
      - RHEL-07-040300
      - SV-86899r1_rule
      - V-72275

- name: "LOW | V-72281 | For systems using DNS resolution, at least two name servers must be configured."
  command: "true"
  tags:
      - cat3
      - low
      - patch
      - RHEL-07-040600
      - SV-86905r1_rule
      - V-72281

