---

- name: "HIGH | V-71961, V-71963 | Systems must require authentication upon booting into single-user and maintenance modes."
  template:
      src=templates/user.cfg
      dest=/boot/grub2/user.cfg
      owner=root
      group=root
      mode=0600
  tags:
      - cat1-grub
      - RHEL-07-010480
      - SV-86585r1_rule
      - V-71961
      - RHEL-07-010490
      - SV-86587r1_rule
      - V-71963
